### ISSUE TITLE
1.4.3: `accordion_credential_shortcode()` - shortcodes must not output content

### ISSUE THREAD

**Issue by lkraav** [accredible/accredible-certificates#12]
https://github.com/accredible/accredible-certificates/blob/master/accredible_widget.php#L116-L129 has a significant boo-boo.

Shortcode functions must only return content, never echo. Either ob-capture it, or build a string variable and return.

This is affecting various AJAX and WP-CLI operations.

**Comment by alanheppenstall** [comment]
Resolved in 1.4.4
