### ISSUE TITLE
Not showing download button after complete the course

### ISSUE THREAD

**Issue by shaikjilanni29** [accredible/accredible-certificates#5]
hi sir,
i m include the code in acadamy theme, but not showing the download certificate button after complete coure please give me instruction how to display the button

**Comment by alanheppenstall** [comment]
Hi @shaikjilanni29 

Please can you let me know what version of Academy Theme you're using?

**Comment by shaikjilanni29** [comment]
2.15 version i using, if any solution for other themes to put the download button for particular user

**Comment by shaikjilanni29** [comment]
please help me

**Comment by alanheppenstall** [comment]
Hi @shaikjilanni29

For now we've dropped Academy Theme support.

We've added a shortcode and widget so you should be able to use them to render certificates & badges for your WP users.
