### ISSUE TITLE
Problem with courses and groups on accreddit

### ISSUE THREAD

**Issue by cyph3rlunch** [accredible/accredible-certificates#7]
Hi, the plugin does not seem to create a group on accredit via the API nor does it allow any kind of link between the course or the group to be used.

Could this plugin perhaps not be working on latest wordpress?

**Comment by alanheppenstall** [comment]
Hello!

We've tested on Wordpress 4.9.7 and the plugin works as expected.

Can you let me know what you're seeing?

**Comment by cyph3rlunch** [comment]
The plugin when using the manual button does work yes. The integration with the Academy theme where it creates a certificate for each person that completes the course does not work. Also, the video published about the plugin does not explain how to set up the plugin with academy.

**Comment by alanheppenstall** [comment]
@cyph3rlunch we removed support for Academy Theme in this plugin.
